#!/bin/sh

DAEMON=/usr/sbin/ntpd
PIDFILE=/run/ntpd.pid
LOCKFILE=/run/lock/ntpsec-ntpdate

if [ -r /etc/default/ntpsec ]; then
        . /etc/default/ntpsec
fi

if [ "$IGNORE_DHCP" != "yes" ] && [ -e /run/ntpsec/ntp.conf.dhcp ]; then
        NTPD_OPTS="$NTPD_OPTS -c /run/ntpsec/ntp.conf.dhcp"
else
	# List the default -c first, so if the admin has specified -c in
	# NTPD_OPTS, it is honored.
	NTPD_OPTS="-c /etc/ntpsec/ntp.conf $NTPD_OPTS"
fi

NTPD_OPTS="$NTPD_OPTS -u ntpsec:ntpsec"

# Protect the service startup against concurrent ntpdate ifup hooks
(
        if flock -w 180 9; then
                # shellcheck disable=SC2086
                exec $DAEMON -p $PIDFILE $NTPD_OPTS
        else
                echo "Timeout waiting for $LOCKFILE"
                exit 1
        fi
) 9>$LOCKFILE
