debian/ntp-systemd-wrapper usr/libexec/ntpsec
debian/rotate-stats usr/libexec/ntpsec
debian/tmp/lib/systemd/system/ntpsec-wait.service
debian/tmp/lib/systemd/system/ntpsec.service
debian/tmp/usr/bin/ntpleapfetch usr/sbin
debian/tmp/usr/bin/ntpmon
debian/tmp/usr/bin/ntpq
debian/tmp/usr/bin/ntptrace
debian/tmp/usr/sbin/ntpd
debian/tmp/usr/sbin/ntpkeygen
debian/tmp/usr/sbin/ntptime
debian/tmp/usr/sbin/ntpwait
debian/tmp/usr/share/man/man1/ntpmon.1
debian/tmp/usr/share/man/man1/ntpq.1
debian/tmp/usr/share/man/man1/ntptrace.1
debian/tmp/usr/share/man/man5/ntp.conf.5
debian/tmp/usr/share/man/man5/ntp.keys.5
debian/tmp/usr/share/man/man8/ntpd.8
debian/tmp/usr/share/man/man8/ntpkeygen.8
debian/tmp/usr/share/man/man8/ntpleapfetch.8
debian/tmp/usr/share/man/man8/ntptime.8
debian/tmp/usr/share/man/man8/ntpwait.8
